### ISSUE TITLE
Datagrid styles: Why are the inputs only 20% in width? Why are 4 cells styles?

### ISSUE THREAD

**Issue by maethu** [4teamwork/plonetheme.blueberry#107]
The datagrid is dynamic and may contain 10 cells, or only 2.
The Theme should leave the special handling go the integration package. 

Tasks: 
- Only set withs for the actions... they need 1em in width.
- Align everything.

**Comment by jone** [comment]
@bierik I have a table with 2 to 13 columns (dynamically):
![bildschirmfoto 2016-12-14 um 16 38 36](https://cloud.githubusercontent.com/assets/7469/21188463/cde1aa94-c21b-11e6-9ec3-0666f457dfd4.png)

We need a more generic approach for styling that.
More custom stylings in the packages are feasible.
