### ISSUE TITLE
Datetime widgets broken on content_status_history

### ISSUE THREAD

**Issue by jone** [4teamwork/plonetheme.blueberry#113]
The styling of the dropdown of the date / time field on content status history (Workflow status change form) is broken:
![bildschirmfoto 2016-10-25 um 11 12 19](https://cloud.githubusercontent.com/assets/7469/19680085/9fffac46-9aa4-11e6-8014-e8261b0e4102.png)

**Comment by bierik** [comment]
Closed through https://github.com/4teamwork/plonetheme.blueberry/pull/114
