### ISSUE TITLE
Change edit-bar color

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/plonetheme.blueberry#126]
The current edit-bar color will create cancer in the eyes!

Now:
<img width="827" alt="bildschirmfoto 2017-01-19 um 14 55 42" src="https://cloud.githubusercontent.com/assets/557005/22109307/80c9b244-de57-11e6-9d18-ab3f3e0ddca5.png">

Why not using some different colors? Examples:

V1
==
<img width="803" alt="bildschirmfoto 2017-01-19 um 14 59 44" src="https://cloud.githubusercontent.com/assets/557005/22109425/fa3f31f8-de57-11e6-8efb-5e18177f1b55.png">

V2
==
<img width="842" alt="bildschirmfoto 2017-01-19 um 14 55 53" src="https://cloud.githubusercontent.com/assets/557005/22109365/b6457f02-de57-11e6-80f4-5b91d68b5571.png">

**Comment by bierik** [comment]
@elioschmutz could you please make suggestion here. Thx

**Comment by elioschmutz** [comment]
We keep it this way and we'll adjust the color for customer projects if desired.
