### ISSUE TITLE
Table heading styles

### ISSUE THREAD

**Issue by maethu** [4teamwork/plonetheme.blueberry#15]
Currently the primary is used for table headings. by default imho this is fine. 

But in some circumstances e.g if the primary color ist RED, or a simipiliar aggressive color i need to change this. 

The current implementation is like...

``` 
@mixin heading-cell() {
  @include auto-text-color();
  background-color: $color-primary;
}
``` 

I would prefer a variable with default value primary color.

**Comment by bierik** [comment]
Fixed through https://github.com/4teamwork/plonetheme.blueberry/pull/31
