### ISSUE TITLE
Schatten bei Bildern

### ISSUE THREAD

**Issue by bbuehlmann** [4teamwork/plonetheme.blueberry#16]
Oft macht man Screenshots eines Ausschnitts einer Website. Dieser Screenshot ist dann nicht gut abgegrenzt gegenüber dem Text.

Idealerweise sollte ein Schatten hinzugefügt werden können. Evt. kann man dies via CSS lösen.

<img width="1265" alt="bildschirmfoto 2016-02-10 um 10 38 52" src="https://cloud.githubusercontent.com/assets/1231822/12944633/a8ed7248-cfe8-11e5-9b6b-08ef0dbc328e.png">

Wo kann man im plonetheme.blueberry eigenes CSS hinzufügen? Früher bei teamraum.theme konnte man dies through-the-web.

**Comment by jone** [comment]
Ich würde dies mit einem Screenshot-Tool lösen. Bzw. wenn ich einen Screenshot mache hat der Screenshot immer bereits einen schönen Rahmen von OSX:
![bildschirmfoto 2016-05-04 um 11 20 11](https://cloud.githubusercontent.com/assets/7469/15010030/4293d43a-11ea-11e6-9903-09af4e3c0605.png)

Es gibt da diverse Tools die schöne Screenshots machen, bzw. mit Snagit kann man alles mögliche einstellen.

---

Grundsätzlich ist ftw.simplelayout nicht auf screenshots optimiert sondern aus meiner Sicht eher für Fotos, welche nicht einen weissen Hintergrund haben.

---

**Bez. CSS-Feld:**
Ein CSS-Feld birgt auch gefahren: es kann Problematisch sein wenn der Kunde selber CSS erfasst, ich denke das wollen wir standardmässig nicht haben und nur auf expliziten Wunsch mit guter Begründung direkt in einem Projekt umsetzen.
Daher denke ich dass nur 4teamwork Mitarbeiter CSS erfassen können sollen. Dies kann momentan einfach mit einem `ploneCustom.css`; wobei dies momentan in der CSS-Registry deaktiviert ist.

---

**Vorschläge:**
- Sofern möglich empfehlen, mit einem guten Screenshot-Tool entsprechende Rahmen direkt im Bild einbetten.
- Wenn eine Seiten-Weite Lösung angestrebt wird sollte dies im `ploneCustom.css` umgesetzt werden [1].

[1] falls dies öfter passiert müssten wir u.U. standardmässig das `ploneCustom.css` aktivieren (es ist ja standardmässig eh leer).

Was denkt ihr dazu?
/cc @maethu

**Comment by bbuehlmann** [comment]
Der Anwendungsfall ist wie folgt: Ich möchte ein Bild hochladen und dann den Border anpassen. Und zwar nur bei diesem einen Bild.

Ich möchte ein anderes Bild hochalden und dort einen Schattenwurf haben. 

Biedes muss aber nur für dieses eine Bild gelten, nicht für alle anderen.

Somit wäre ein CSS Feld praktisch.

**Comment by maethu** [comment]
Ich wäre Grundsätzlich für ein gutes Screenshot-Tool, habe sehr gute Erfahrungen mit SnagIt gemacht. 

Falls diese Funktion für eine Website gewünscht wird, bin dafür, dass diese Funktion in dieser Policy implementiert wird. Bisher hatte noch keiner ftw.simplelayout-Kunde diese Anforderung. Es gilt zu Bedenken, wenn diese Feature in ftw.simplelayout integriert wird und dies nur einmal Benutzt wird, müssen wir es bei allen anderen entfernen.

**Comment by bbuehlmann** [comment]
Ok, so könnten wir es vielleicht in unsere zukünftige Policy für www.4teamwork.ch einbauen.

**Comment by jone** [comment]
👍 Super, dann machen wir vorerst mal nichts und schauen das dann im Rahmen vom Relaunch der Website an.
