### ISSUE TITLE
datetime fields too large

### ISSUE THREAD

**Issue by jone** [4teamwork/plonetheme.blueberry#3]
Datetime (e.g. effective dates): the date / month / year fields are too large

![bildschirmfoto 2016-02-05 um 15 36 15](https://cloud.githubusercontent.com/assets/7469/12849119/34aa95a0-cc1e-11e5-9296-dfd672c4fba9.png)

**Comment by bierik** [comment]
@jone How do I get these field. If I want to edit the contentpage I just get the title and description.

**Comment by jone** [comment]
In `portal_types` -> `ftw.simplelayout.ContentPage (ContentPage)`, add the behavior
`plone.app.dexterity.behaviors.metadata.IPublication` (assuming you have an ftw.simplelayout-setup)

**Comment by bierik** [comment]
I have blueberry and simplelayout contentypes default installed but I just get these behaviors:

![bildschirmfoto 2016-03-02 um 08 33 56](https://cloud.githubusercontent.com/assets/1637820/13453607/b7ee3100-e051-11e5-95d1-f410f86b5b42.png)

**Comment by jone** [comment]
@bierik yes, you need manually add the behavior `plone.app.dexterity.behaviors.metadata.IPublication` i order to get the date fields :wink:
