### ISSUE TITLE
Search: hide "in current folder only"

### ISSUE THREAD

**Issue by jone** [4teamwork/plonetheme.blueberry#33]
@bbuehlmann and I have decided that we currently want to hide "in current folder only" by default.
Depending on the project it should be possible to easily enable it again, e.g. with CSS `display: block`.
![bildschirmfoto 2016-02-19 um 17 54 30](https://cloud.githubusercontent.com/assets/7469/13182534/8a98d2d2-d732-11e5-950c-b51ae720a5ba.png)

**Comment by bierik** [comment]
Fixed through https://github.com/4teamwork/plonetheme.blueberry/pull/40/files#diff-f2cdd2cf0daaf7b005c264ced551990bR6
