### ISSUE TITLE
News ohne Bild eingerückt

### ISSUE THREAD

**Issue by jone** [4teamwork/plonetheme.blueberry#35]
https://webdemo.4teamwork.ch/pk_ewg/news
![bildschirmfoto 2016-02-24 um 15 39 43](https://cloud.githubusercontent.com/assets/7469/13288579/df4956a2-db0c-11e5-8385-80da23692a28.png)

Die News-Meldungen sind eingerückt, obwohl ja gar kein Bild da ist. Sieht etwas komisch aus.

/cc @mtokmak

**Comment by bierik** [comment]
@jone was hältst du von einem Platzhalter bild

**Comment by bierik** [comment]
@jone okay i sehe das problem. es ist nicht das fehlende bild sondern der abstand, der immer da ist auch wenn ausgewählt ist, dass kein bild erscheinen soll
