### ISSUE TITLE
Dropdown bei Teaserverlinkung

### ISSUE THREAD

**Issue by raphael-s** [4teamwork/plonetheme.blueberry#48]
Wenn bei der Teaserauswahl das Dropdown geöffnet ist und man dann neben dem Dialog herumscrollt, wird die Seite hinter dem Dialog mitsamt Dropdown bewegt.

Das Gleiche passiert auch beim öffnen vom Kontextmenu in einem Textfeld durch Rechtsklick. Das Kontextmenu hefftet sich auch hier an den Hintergrund und nicht an das Overlay.

Beispiel:
![bildschirmfoto 2016-03-31 um 13 55 51](https://cloud.githubusercontent.com/assets/16755391/14175046/c7944b04-f748-11e5-9cda-75c127494725.png)
![bildschirmfoto 2016-03-31 um 13 56 39](https://cloud.githubusercontent.com/assets/16755391/14175047/c7958640-f748-11e5-9913-a7716f4f4106.png)

**Comment by bierik** [comment]
The content is no longer scrollable since https://github.com/4teamwork/plonetheme.blueberry/commit/fe947763091b#diff-daad10898d1d2719006a5d79428e6212R21
