### ISSUE TITLE
always show scrollbar?

### ISSUE THREAD

**Issue by jone** [4teamwork/plonetheme.blueberry#5]
Because we have a centered layout and pages may or may not have scrollbars (long vs. short pages) we will experience a flickering clicking around the website.
See:
![bildschirmfoto 2016-02-08 um 14 33 31](https://cloud.githubusercontent.com/assets/7469/12887037/0a3573c0-ce72-11e5-91c1-015ab084619f.png)
--
As described in http://stackoverflow.com/questions/9650762/how-to-compensate-for-vertical-scrollbar-when-it-is-not-yet-present, we could eliminate the flickering by always showing a scrollbar (since we usually have longer content):
```css
body {
  overflow-y: scroll
}
```
What do you think about that?

**Comment by bierik** [comment]
Fixed through https://github.com/4teamwork/plonetheme.blueberry/pull/39
