### ISSUE TITLE
Header Bereich verdeckt das Menü vollständig

### ISSUE THREAD

**Issue by phgross** [4teamwork/plonetheme.blueberry#67]
![bildschirmfoto 2016-06-21 um 16 34 41](https://cloud.githubusercontent.com/assets/485755/16233266/12c9f630-37ce-11e6-8420-a135ca15d049.png)

https://onegovgever.ch/geschaeftsverwaltung

@bierik bitte ASAP anschauen, wir sollten hier Inhalt erfassen können und das ist im Moment nicht möglich 😏

**Comment by bierik** [comment]
Fixed through https://github.com/4teamwork/plonetheme.blueberry/commit/cb6870b4d6316933bcd89c992d42c6e19833e663
