### ISSUE TITLE
No theme is enabled when creating a new plonesite

### ISSUE THREAD

**Issue by raphael-s** [4teamwork/plonetheme.blueberry#94]
In the appearance panel no theme (standard, government or marketing) is enabled.

**Comment by bierik** [comment]
@jone hast du da eine idee? ich habs schon versucht aber ohne erfolg. Im `theme.xml` ist das standard Theme als enabled markiert

**Comment by jone** [comment]
You need to select the theme you want to activate..

Please describe what you did (which buttons clicked, which checkboxes checked) and what you expect (which design enabled).

**Comment by bierik** [comment]
The ticket description is not specific enough so the problem can not be reproduced.
